fnielsen/ordia

- ordia/app/templates/text_to_lexemes.html
I have added support to 3 languages: Spanish, Hindi and Malayalam
> Add support for more languages

- ordia/app/static/lexemeforms.js
- ordia/app/templates/search.html
- ordia/app/templates/text_to_lexemes.html
- ordia/app/views.py
> Buttons to send new lexeme to lexeme-forms tool (in specified language)

- ordia/app/templates/text_to_lexemes.html
- ordia/app/views.py
This is related to #82 which suggest filtering on casing.
> Implement casing in text-to-lexemes

- ordia/app/templates/statistics.html
Link from identifier statistics panel in statistics aspect to property aspect
implemented.  #101
> Implement link from identifier to property #101

- ordia/app/templates/statistics.html
* [Property:P8478](https://www.wikidata.org/wiki/Property:P8478) Svenska Akademiens Ordbok ID
* used on [w.wiki/rwk](https://w.wiki/rwk)
> Added Svenska Akademiens Ordbok ID P8478 to template statistics.html

- ordia/text.py
> Fix error where two letters are shortened to one

- ordia/app/templates/lf.html
Here it is for https://www.wikidata.org/wiki/Lexeme:L99#F6
> add Wikiquote panel to Lexeme Form profile

- ordia/app/templates/lf.html
> Adjusted the wikisourcesparql srsearch string

- ordia/app/templates/lf.html
Making the search on Wikiquote on the representation narrower by quoting the representation
> Fix #160 quote on search in wikiquote

- ordia/query.py
- requirements.txt
- tox.ini
This fix includes requirement updates of Werkzeug and Flask Fix of style in query.py
Change of tox test to Python39
> Fix #182 werkzeug security issue.

- requirements.txt
> Fix #192 security issue in requests

- ordia/app/templates/guess-the-gender.html
The Guess the Gender game now starts with language select so other languages than Danish can be used.
> Fix #207 language selection for gender guess

- ordia/app/templates/language.html
Add toponym map to language aspect
> Fix #185 Toponym map

- ordia/app/templates/base.html
- ordia/app/templates/guess-word-from-image.html
Now with more language.
Menu change
Color on icons
Slight code cleanup
> Fix #216 Guess word from image cleanup

- ordia/app/templates/guess-word-from-image.html
Guess-word-from-image had a multiple lemma problem that affect, e.g., Japanese, Punjabi and Turkish. Now lemma are concatenated.
> Fix #218 multiple lemma problem

- ordia/app/templates/flying-dehyphenator.html
Add more languages based on SPARQL query
> Fix #228 Flying Dehyphenator languages

- ordia/app/templates/game_index.html
- ordia/app/templates/guess-image-from-pronunciation.html
- ordia/app/templates/guess-word-from-pronunciation.html
Better randomization in Guess Word From Pronunciation This PR include styling of the Javascript with change of indentation. Furthermore there is a fix on the game index page
> Fix #242 Better randomization in game

- ordia/app/templates/lexical_category_language.html
Table with grammatical features statistical for
lexical-category-language aspect
> Fix #238 Grammatical features statistics

- ordia/app/templates/l.html
"Lexemes that have this lexeme as part"
> Fix #154 Rename compounds

- ordia/app/templates/guess-form-from-text.html
> Fix #266: implement guess form from text game

- ordia/app/templates/guess-the-gender.html
- ordia/app/templates/guess-word-from-pronunciation.html
add punjabi language (Q58635) to these games: guess-word-from-pronunciation and guess-the-gender
> add punjabi (pa) to guess-word-from-pronunciation and guess-the-gender

- ordia/app/templates/guess-form-from-text.html
Add warning message for no data in guess form from text game.
This PR also include a fix for proclitics in the regular expression for French.
> Partial fix for #274 no data for games
